name: use-click-outside
 
on:  
  push:
  pull_request:
    branches:
      - master
 
jobs:
  build:
    name: use-click-outside
    timeout-minutes: 15
    runs-on: ubuntu-latest
 
    steps:
      - name: Check out code
        uses: actions/checkout@v4
 
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci
        working-directory: ./packages/use-click-outside

      - name: Build project
        run: npm run build
        working-directory: ./packages/use-click-outside